# Generated by Django 5.0.1 on 2024-01-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('credit_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='credit_application.creditapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
